' Daily Morning Report Script
' Runs at 7:00 AM daily to send system status email
' Author: Generated for Ron Nicol
' Date: January 22, 2026

Sub Main(Parm As Object)
    Try
        ' Build the email report
        Dim emailBody As String = BuildDailyReport()
        Dim emailSubject As String = "Daily Home Status Report - " & DateTime.Now.ToString("M/d/yyyy")
        
        ' Send email using .NET SmtpClient
        Dim smtp As New System.Net.Mail.SmtpClient("192.168.4.69")
        smtp.Port = 25
        smtp.EnableSsl = False
        smtp.UseDefaultCredentials = False
        smtp.Credentials = New System.Net.NetworkCredential("alerts@ens-stars.com", "Iwilln1v1rgu1ss")
        
        Dim mailMsg As New System.Net.Mail.MailMessage()
        mailMsg.From = New System.Net.Mail.MailAddress("alerts@ens-stars.com")
        mailMsg.To.Add("rnicol@1975.usna.com")
        mailMsg.To.Add("liane73fsu@hotmail.com")
        mailMsg.Subject = emailSubject
        mailMsg.Body = emailBody
        mailMsg.IsBodyHtml = True
        
        smtp.Send(mailMsg)
        
        hs.WriteLog("DailyReport", "Email sent successfully")
        
    Catch ex As Exception
        hs.WriteLog("DailyReport", "ERROR: " & ex.Message)
    End Try
End Sub

Function BuildDailyReport() As String
    Dim sb As New System.Text.StringBuilder()
    
    ' Header
    sb.AppendLine("<html><head><style>")
    sb.AppendLine("body { font-family: Arial, sans-serif; margin: 20px; }")
    sb.AppendLine("h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }")
    sb.AppendLine("h2 { color: #34495e; margin-top: 25px; border-bottom: 1px solid #bdc3c7; padding-bottom: 5px; }")
    sb.AppendLine("table { border-collapse: collapse; width: 100%; margin: 15px 0; }")
    sb.AppendLine("th { background-color: #3498db; color: white; padding: 10px; text-align: left; }")
    sb.AppendLine("td { padding: 8px; border-bottom: 1px solid #ecf0f1; }")
    sb.AppendLine("tr:nth-child(even) { background-color: #f8f9fa; }")
    sb.AppendLine(".alert { background-color: #e74c3c; color: white; padding: 10px; border-radius: 5px; margin: 10px 0; }")
    sb.AppendLine(".sun-info { background-color: #f39c12; color: white; padding: 15px; border-radius: 5px; margin: 10px 0; }")
    sb.AppendLine("</style></head><body>")
    
    sb.AppendLine("<h1>🏠 Daily Home Status Report</h1>")
    sb.AppendLine("<p><strong>Date:</strong> " & DateTime.Now.ToString("MMMM dd, yyyy") & "</p>")
    sb.AppendLine("<p><strong>Time:</strong> " & DateTime.Now.ToString("h:mm tt") & "</p>")
    
    ' Sunrise/Sunset Section
    sb.AppendLine("<h2>☀️ Sun Information</h2>")
    sb.AppendLine("<div class='sun-info'>")
    Dim sunrise As Date = hs.SunRise()
    Dim sunset As Date = hs.SunSet()
    sb.AppendLine("<strong>Sunrise:</strong> " & sunrise.ToString("h:mm tt") & "<br>")
    sb.AppendLine("<strong>Sunset:</strong> " & sunset.ToString("h:mm tt") & "<br>")
    Dim dayLength As TimeSpan = sunset.Subtract(sunrise)
    sb.AppendLine("<strong>Day Length:</strong> " & dayLength.Hours & " hours " & dayLength.Minutes & " minutes")
    sb.AppendLine("</div>")
    
    ' Thermostats Section
    sb.AppendLine("<h2>🌡️ Climate Control Status</h2>")
    sb.AppendLine("<table>")
    sb.AppendLine("<tr><th>Location</th><th>Temp</th><th>Humidity</th><th>Heat SP</th><th>Cool SP</th><th>System Mode</th><th>Fan Mode</th><th>Fan Status</th></tr>")
    
    ' Living Room: 642,643,645,646,637,638,640,641
    sb.AppendLine(GetThermostatRow("Living Room", 642, 643, 646, 645, 637, 640, 641))
    
    ' Master Bedroom: 654,655,657,658,649,650,652,653
    sb.AppendLine(GetThermostatRow("Master Bedroom", 654, 655, 658, 657, 649, 652, 653))
    
    ' Media Room: 462,463,465,466,457,458,460,461
    sb.AppendLine(GetThermostatRow("Media Room", 462, 463, 466, 465, 457, 460, 461))
    
    sb.AppendLine("</table>")
    
    ' Low Battery Shades Section
    Dim lowBatteryShades As String = GetLowBatteryShades()
    If lowBatteryShades <> "" Then
        sb.AppendLine("<h2>🔋 Low Battery Alerts</h2>")
        sb.AppendLine("<div class='alert'>")
        sb.AppendLine("<strong>⚠️ The following shades have battery levels at or below 25%:</strong><br><br>")
        sb.AppendLine(lowBatteryShades)
        sb.AppendLine("</div>")
    Else
        sb.AppendLine("<h2>🔋 Battery Status</h2>")
        sb.AppendLine("<p style='color: green; font-weight: bold;'>✓ All shades have adequate battery levels (>25%)</p>")
    End If
    
    ' Footer
    sb.AppendLine("<hr style='margin-top: 30px;'>")
    sb.AppendLine("<p style='font-size: 12px; color: #7f8c8d;'>")
    sb.AppendLine("This is an automated report generated by HomeSeer 4.<br>")
    sb.AppendLine("Report generated at " & Now().ToString("h:mm:ss tt") & " on " & Now().ToString("MMMM dd, yyyy") & ".")
    sb.AppendLine("</p>")
    sb.AppendLine("</body></html>")
    
    Return sb.ToString()
End Function

Function GetThermostatRow(location As String, tempRef As Integer, humidityRef As Integer, heatRef As Integer, coolRef As Integer, systemModeRef As Integer, fanModeRef As Integer, fanStatusRef As Integer) As String
    Dim sb As New System.Text.StringBuilder()
    
    Try
        ' Get temperature
        Dim tempVal As Double = hs.DeviceValue(tempRef)
        Dim tempValue As String = String.Format("{0:F1}°F", tempVal)
        
        ' Get humidity
        Dim humidityVal As Double = hs.DeviceValue(humidityRef)
        Dim humidityValue As String = String.Format("{0:F0}%", humidityVal)
        
        ' Get heat setpoint
        Dim heatVal As Double = hs.DeviceValue(heatRef)
        Dim heatValue As String = String.Format("{0:F0}°F", heatVal)
        
        ' Get cool setpoint
        Dim coolVal As Double = hs.DeviceValue(coolRef)
        Dim coolValue As String = String.Format("{0:F0}°F", coolVal)
        
        ' Get system mode text
        Dim systemModeVal As Double = hs.DeviceValue(systemModeRef)
        Dim systemMode As String = GetStatusText(systemModeRef, systemModeVal)
        
        ' Get fan mode text
        Dim fanModeVal As Double = hs.DeviceValue(fanModeRef)
        Dim fanMode As String = GetStatusText(fanModeRef, fanModeVal)
        
        ' Get fan status text
        Dim fanStatusVal As Double = hs.DeviceValue(fanStatusRef)
        Dim fanStatus As String = GetStatusText(fanStatusRef, fanStatusVal)
        
        ' Build row
        sb.Append("<tr>")
        sb.Append("<td><strong>" & location & "</strong></td>")
        sb.Append("<td>" & tempValue & "</td>")
        sb.Append("<td>" & humidityValue & "</td>")
        sb.Append("<td>" & heatValue & "</td>")
        sb.Append("<td>" & coolValue & "</td>")
        sb.Append("<td>" & systemMode & "</td>")
        sb.Append("<td>" & fanMode & "</td>")
        sb.Append("<td>" & fanStatus & "</td>")
        sb.Append("</tr>")
        
    Catch ex As Exception
        hs.WriteLog("DailyReport", "ERROR in GetThermostatRow for " & location & ": " & ex.Message)
        Return "<tr><td colspan='8'>" & location & " - Error: " & ex.Message & "</td></tr>"
    End Try
    
    Return sb.ToString()
End Function

Function GetStatusText(devRef As Integer, value As Double) As String
    Try
        ' Get all status pairs for this device (returns VSPair array)
        Dim pairs As Object = hs.DeviceVSP_GetAllStatus(devRef)
        
        If pairs IsNot Nothing AndAlso pairs.Length > 0 Then
            ' Iterate through the array to find matching value
            For Each pair As Object In pairs
                If pair.Value = value Then
                    Return pair.Status
                End If
            Next
        End If
        
        ' No VSPair data - handle common binary values
        If value = 0 Then
            Return "Off"
        ElseIf value = 1 Then
            Return "On"
        End If
        
    Catch ex As Exception
        hs.WriteLog("DailyReport", "ERROR in GetStatusText for ref " & devRef & ": " & ex.Message)
    End Try
    
    ' Fall back to numeric value
    Return value.ToString()
End Function

Function GetLowBatteryShades() As String
    Dim sb As New System.Text.StringBuilder()
    Dim foundLowBattery As Boolean = False
    
    Try
        ' Search all devices for PowerView shades with low battery
        Dim devEnum As Object = hs.GetDeviceEnumerator()
        
        If devEnum IsNot Nothing Then
            Do
                Dim dev As Object = devEnum.GetNext()
                If dev Is Nothing Then Exit Do
                
                Dim shadeName As String = dev.get_Name(hs)
                Dim shadeLocation As String = dev.get_Location(hs)
            
            ' Look for shade devices (PowerView plugin)
            If shadeLocation.Contains("PowerView") Or shadeName.Contains("Shade") Then
                ' Check for battery-related associated devices (returns Integer array)
                Dim assocDevices As Integer() = dev.AssociatedDevices(hs)
                If assocDevices IsNot Nothing AndAlso assocDevices.Length > 0 Then
                    For Each childRef As Integer In assocDevices
                        Dim childDev As Object = hs.GetDeviceByRef(childRef)
                        If childDev IsNot Nothing Then
                            Dim childName As String = childDev.get_Name(hs)
                            
                            ' Look for battery strength feature
                            If childName.Contains("Battery") And Not childName.Contains("Status") Then
                                Dim batteryLevel As Double = hs.DeviceValueEx(childRef)
                                
                                If batteryLevel <= 25 And batteryLevel > 0 Then
                                    foundLowBattery = True
                                    sb.AppendLine("• <strong>" & shadeName & "</strong> - Battery: " & batteryLevel.ToString("0") & "%<br>")
                                End If
                            End If
                        End If
                    Next
                End If
            End If
            Loop
        End If
        
    Catch ex As Exception
        hs.WriteLog("DailyReport", "Error checking shade batteries: " & ex.Message)
        Return "<p>Error checking battery levels: " & ex.Message & "</p>"
    End Try
    
    If foundLowBattery Then
        Return sb.ToString()
    Else
        Return ""
    End If
End Function
